name: NLP Text Classification CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  train-and-register:
    runs-on: ubuntu-latest

    env:
      AML_SUBSCRIPTION_ID: ${{ secrets.AML_SUBSCRIPTION_ID }}
      AML_RESOURCE_GROUP: ${{ secrets.AML_RESOURCE_GROUP }}
      AML_WORKSPACE: ${{ secrets.AML_WORKSPACE }}
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade azure-ai-ml
        pip install --upgrade azureml-mlflow
        pip install azure-ai-ml joblib scikit-learn pandas azure-identity jq
        pip install marshmallow==3.20.1



    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Export Azure SP credentials as environment variables
      run: |
        echo "$AZURE_CREDENTIALS" > creds.json
        echo "AZURE_CLIENT_ID=$(jq -r .clientId creds.json)" >> $GITHUB_ENV
        echo "AZURE_TENANT_ID=$(jq -r .tenantId creds.json)" >> $GITHUB_ENV
        echo "AZURE_CLIENT_SECRET=$(jq -r .clientSecret creds.json)" >> $GITHUB_ENV

    - name: Prepare folders and data
      run: |
        mkdir -p data/raw data/processed models
        cp data/nlp_text_classification_dataset_2000.csv data/raw/ || true

    - name: Run Data Validation
      run: python src/data_validation.py

    - name: Run Preprocessing
      run: python src/preprocessing.py

    - name: tracking uri
      run: python src/uri.py

    # - name: Train Model and Log to Azure MLflow
    #   run: python src/train.py

    # - name: Evaluate Model and Log Metrics
    #   run: python src/evaluate.py

    # - name: Register Model to Azure ML
    #   run: python src/register_model.py

    # Optional: Deploy model if desired
    - name: Deploy Model
      run: python src/deploy_model.py
